version: '3'
services:
  web-python:
    build: ./web
    environment:
     - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
    ports:
     - "80:5000"
  database-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: